title: SteinSyne
description: My website to chronicle my cyber endeavors.
author: Landin Stein
avatar: /headshot.png
email: landinstein15@gmail.com

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

#remote_theme: steinsyne/jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: 
  card: summary
logo: headshot.png
social:
  name: Landin Stein
  links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://github.com/SteinSyne
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
